# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tim Rogers
email: me@timrogers.co.uk
description: Tim Rogers is based in London, UK and leads product at Duffel. Before Duffel, he was an early employee at GoCardless and ran his own startup, Reward Flight Finder.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://timrogers.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - scripts
  - s3_website.yml
  - .DS_Store
  - Dockerfile
  - docker-compose.yml
