version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/ruby:3.0.2
    steps:
      - checkout

      - type: cache-restore
        key: timrogers-bundler-v2-{{ checksum "Gemfile.lock" }}

      - run: bundle install --path vendor/bundle

      - type: cache-save
        key: timrogers-bunder-v2-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - run: bundle exec jekyll build

      - run: bundle exec scripts/test
  build-and-deploy:
    docker:
      - image: circleci/ruby:3.0.2
    steps:
      - checkout

      - run: sudo apt-get update

      - run: sudo apt-get install --assume-yes openjdk-8-jre

      - type: cache-restore
        key: timrogers-bundler-v1-{{ checksum "Gemfile.lock" }}

      - run: bundle install --path vendor/bundle

      - type: cache-save
        key: timrogers-bunder-v1-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - type: cache-restore
        key: timrogers-yarn-v1-{{ checksum "yarn.lock" }}

      - run: yarn install

      - type: cache-save
        key: timrogers-yarn-v1-{{ checksum "yarn.lock" }}
        paths:
          - "~/.cache/yarn"
          - "~/.yarn"

      - run: node_modules/.bin/gulp assets:build

      - run: bundle exec jekyll build

      - run: bundle exec s3_website install

      - run: java -cp $(bundle show s3_website)/*.jar s3.website.Push
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build-and-test
      - build-and-deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
