version: 2.1
orbs:
  ruby: circleci/ruby@1.0
jobs:
  build-and-test:
    docker:
      - image: cimg/ruby:3.0.2
    steps:
      - checkout
      - ruby/install-deps
      - run: bundle exec jekyll build
      - run: bundle exec scripts/test
  build-and-deploy:
    docker:
      - image: timrogers/ruby-with-openjdk-8-jre:3.0.2
    steps:
      - checkout
      - ruby/install-deps
      - run: bundle exec jekyll build
      - run: bundle exec s3_website install
      - run: java -cp $(bundle show s3_website)/*.jar s3.website.Push
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build-and-test
      - build-and-deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
