#!/usr/bin/env ruby
# frozen_string_literal: true
require "html-proofer"

puts `bundle exec jekyll build --drafts`

HTMLProofer.check_directory('./_site', 
                            url_swap: {
                              'https://timrogers.co.uk' => '',
                            },
                            url_ignore: [
                              'https://www.shopping.ba.com/*'
                            ],
                            typhoeus: {
                              headers: HTMLProofer::Configuration::TYPHOEUS_DEFAULTS[:headers].merge({
                                "Accept" => "text/html"
                              })
                            }).run