#!/usr/bin/env ruby
# frozen_string_literal: true
require "html-proofer"

puts `bundle exec jekyll build --drafts`

HTMLProofer.check_directory('./_site', 
                            swap_urls: {
                              'https://timrogers.co.uk' => '',
                            },
                            ignore_urls: [
                              /shopping\.ba\.com/,
                              /estore\.aerlingus\.com/,
                              /genius\.com/,
                            ],
                            typhoeus: {
                              headers: HTMLProofer::Configuration::TYPHOEUS_DEFAULTS[:headers].merge({
                                "Accept" => "text/html"
                              })
                            }).run